# Generated by Django 3.0.8 on 2020-11-02 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
